version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Update Python dependencies
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
